import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
//import i18n from "i18next";
//import { initReactI18next } from "react-i18next";
//import LanguageDetector from "i18next-browser-languagedetector";




const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const browserLanguage = navigator.language 

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang={browserLanguage}>
			<body className={inter.variable}>
				<AuthProvider>	<Theme accentColor="gold">
					{/* <ThemePanel/> */}
					<NavBar />
					<main className="p-5">
						<Container>{children}</Container>
					</main>
				</Theme>	
				</AuthProvider>
			
			</body>
		</html>
	);
}
